OCAMLC=ocamlc
OCAMLDEP=ocamldep
OFLAGS=-w A # warn about everything

SRC_FILES = parse.ml
EXECUTABLE = swagger
OPAM_PACKAGES = yojson

LIBS = str.cmxa

DEPS_FILE = ocamldep.mk

include $(DEPS_FILE)

build: clean schema.cmi
	ocamlfind ocamlopt -o $(EXECUTABLE) $(LIBS) $(SRC_FILES) -package $(OPAM_PACKAGES) -linkpkg

clean:
	rm -f $(EXECUTABLE) *.cmo *.cmi

%.cmo: %.ml
	$(OCAMLC) $(OFLAGS) -c $<

%.cmi: %.mli
	$(OCAMLC) $(OFLAGS) -c $<

# Generated by ocamldep *.mli *.ml
dependencies:
	$(OCAMLDEP) *.mli *.ml > $(DEPS_FILE)
